# Base de datos
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=booklibrary
quarkus.datasource.password=booklibrary
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5435/booklibrary

# Hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true

# Puerto
quarkus.http.port=8080

# Swagger UI
quarkus.swagger-ui.always-include=true